part of app_module;

class AppCoins {
  static final defaultCoins = [
    CoinInfo(
      chain: 'BTC',
      symbol: 'BTC',
      name: 'BTC',
      fullName: 'Bitcoin',
      iconLocal: 'assets/images/coin_btc.png',
      isEnabled: true,
      isFixed: false,
      chainPrecision: 18,
      displayPrecision: 8,
    ),
    CoinInfo(
      chain: 'BBC',
      symbol: 'BBC',
      name: 'BBC',
      fullName: 'BigBang Core',
      iconLocal: 'assets/images/coin_bbc.png',
      isEnabled: true,
      isFixed: true,
      chainPrecision: 6,
      displayPrecision: 6,
      contract:
          '00000000b0a9be545f022309e148894d1e1c853ccac3ef04cb6f5e5c70f41a70',
    ),
    CoinInfo(
      chain: 'ETH',
      symbol: 'ETH',
      name: 'ETH',
      fullName: 'Ethereum',
      iconLocal: 'assets/images/coin_eth.png',
      isEnabled: true,
      isFixed: false,
      chainPrecision: 18,
      displayPrecision: 8,
    ),
    CoinInfo(
      chain: 'TRX',
      symbol: 'TRX',
      name: 'TRX',
      fullName: 'TRON',
      iconLocal: 'assets/images/coin_trx.png',
      isEnabled: true,
      isFixed: false,
      chainPrecision: 6,
      displayPrecision: 6,
    ),
    CoinInfo(
      chain: 'ETH',
      symbol: 'USDT',
      name: 'USDT-ERC20',
      fullName: 'Tether USD (ERC20)',
      iconLocal: 'assets/images/coin_usdt_erc.png',
      isEnabled: true,
      isFixed: false,
      contract: '0xdac17f958d2ee523a2206206994597c13d831ec7',
      chainPrecision: 6,
      displayPrecision: 6,
    ),
    CoinInfo(
      chain: 'TRX',
      symbol: 'USDT',
      name: 'USDT-TRC20',
      fullName: 'Tether USD (TRC20)',
      iconLocal: 'assets/images/coin_usdt_trx.png',
      isEnabled: true,
      isFixed: false,
      chainPrecision: 6,
      displayPrecision: 6,
    ),
    // App Specific coins
    CoinInfo(
      chain: 'BBC',
      symbol: 'SUG',
      name: 'SUG',
      fullName: 'Sugar',
      iconLocal: 'assets/images/coin_sug.png',
      isEnabled: true,
      isFixed: false,
      chainPrecision: 6,
      displayPrecision: 6,
      contract:
          '0008cfddac01c6d1b290d1fcde2177fabebdab6bdb49524d42232b94f518e209',
    ),
  ];
}
